version: 0.0
os: linux

files:
  - source: /  # This means we will deploy the entire repository
    destination: /var/www/my-app  # The destination on the EC2 instance

hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
